name: lazyext
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  google_sign_in: ^6.1.4
  http: ^1.1.0
  firebase_analytics: ^10.4.4
  googleapis: ^11.3.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.10
  provider: ^6.0.5
  googleapis_auth: ^1.4.1
  go_router: ^10.0.0
  infinite_scroll_pagination: ^4.0.0
  flutter_pdfview: ^1.3.1
  _discoveryapis_commons: ^1.0.6
  path_provider: ^2.0.15
  image: ^4.0.17
  pdfx: ^2.4.0
  jnigen:
    git:
      url: https://github.com/dart-lang/jnigen
      ref: main
      path: jnigen
  jni:
    git:
      url: https://github.com/dart-lang/jnigen
      ref: main
      path: jni
  mupdf_android:
    path: ../mupdf_flutter
  file: ^6.0.0
  file_picker: ^5.3.3
  uuid: ^3.0.7
  shared_preferences: ^2.2.0
  background_fetch: ^1.2.1
  flutter_profile_picture: ^2.0.0
  intl: ^0.18.1
  dynamic_color: ^1.6.6
  mutex: ^3.0.1
  flutter_appauth: ^6.0.2
  flutter_dotenv: ^5.1.0
  flutter_local_notifications: ^15.1.1
  multi_select_flutter: ^4.1.3
  async: ^2.11.0
  flutter_expandable_fab: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/logo-cropped.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - .env
